### ISSUE TITLE
It does not work and keeps sending a device connected and disconnected

### ISSUE THREAD

**Issue by rjh05** [pzmarzly/ancs4linux#4]
Exception: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.bluez.Battery1'
Device disconnected
Device connected
Exception: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.bluez.Battery1'
Device disconnected
Traceback (most recent call last):
  File "./main.py", line 30, in <module>
    device = hci.search_for_device()
  File "/home/mystic/ancs4linux-master/Hci.py", line 41, in search_for_device
    connected = props.Get("org.bluez.Device1", "Connected")
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownObject: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" doesn't exist

**Comment by pzmarzly** [comment]
I've rewritten the project, version 1.0 no longer looks at battery state.
